AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 4

Layout/IndentationStyle:
  EnforcedStyle: spaces

Layout/TrailingWhitespace:
  Enabled: false

plugins:
  - rubocop-sorbet
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-minitest