version: '3.8'

services:
  rbdots-test:
    build: .
    container_name: rbdots-sandbox
    volumes:
      # Mount the project directory to allow for live code changes during development
      - .:/home/testuser/rbdots
      # Mount a volume for persistent testing data
      - rbdots-test-data:/home/testuser/.rbdots-test
    environment:
      - RBDOTS_DRY_RUN=true
      - TERM=xterm-256color
    stdin_open: true
    tty: true
    working_dir: /home/testuser/rbdots
    command: /bin/bash -l

volumes:
  rbdots-test-data: 